#!/usr/bin/env bash
# Aggregate every udfs/**/*.sql into a single dist/mariadb-compat.sql that can
# be loaded via exaplus (`@dist/mariadb-compat.sql`) or any tool that honours
# the `/` statement delimiter.
set -euo pipefail

cd "$(dirname "$0")"

OUT="dist/mariadb-compat.sql"
VERSION="$(git describe --tags --always --dirty 2>/dev/null || echo 'dev')"

mkdir -p dist

{
    echo "-- exasol-mariadb-compat ${VERSION}"
    echo "-- Auto-generated by build.sh from udfs/**/*.sql — DO NOT EDIT."
    echo "-- Install:  @dist/mariadb-compat.sql   (exaplus)"
    echo "--     or:   python install.py ...     (pyexasol)"
    echo
    echo "CREATE SCHEMA IF NOT EXISTS UTIL;"
    echo "/"
    echo

    # Stable order: lexical path sort.
    find udfs -name '*.sql' -print0 | sort -z | while IFS= read -r -d '' f; do
        rel="${f#udfs/}"
        echo "-- === ${rel} ==="
        # Strip any trailing ';' or '/' from the source and emit our own '/' terminator.
        sed -e 's/[[:space:]]*;[[:space:]]*$//' -e 's/^[[:space:]]*\/[[:space:]]*$//' "$f"
        echo
        echo "/"
        echo
    done
} > "${OUT}"

lines=$(wc -l < "${OUT}")
echo "Built ${OUT} (${lines} lines, ${VERSION})"
